services:

    tax_manager:
        class: App\TaxManager
        public: true # Services are private by default

    # define your tax implementations
    tax_below_section:
        class: App\LowCalculation
        arguments:
            - 15000
        tags:
            - tax_manager.add

    hra_tax:
        class: App\HRATaxCalculation
        arguments:
            - 95000
        tags:
            - tax_manager.add

    tax_ppf:
        class: App\TaxPPFDeduction
        arguments:
          - 7.0
          - 2000040
        tags:
          - tax_manager.add
